import {applicableVariables,DIMENSIONS,MODEL,Pathology,PRIORITY_CUTS,Dimension} from '../data/stratificationModel';
export type AnswerValue=string|string[]; export type Answers=Record<string,AnswerValue|undefined>;
export type Priority=1|2|3; export type Source='HCE'|'Entrevista al paciente'|'Manual'|'Sugerencia automatizada confirmada';
export function pointsFor(id:string,value:AnswerValue|undefined){const v=MODEL.find(x=>x.id===id);if(!v||value===undefined)return 0;const values=Array.isArray(value)?value:[value];return values.reduce((n,x)=>n+(v.options.find(o=>o.value===x)?.points??0),0)}
export function calculateScore(answers:Answers,pathology?:Pathology){return applicableVariables(pathology).reduce((n,v)=>n+pointsFor(v.id,answers[v.id]),0)}
export function calculateDimensionScores(answers:Answers,pathology?:Pathology){return (Object.keys(DIMENSIONS) as Dimension[]).reduce((a,d)=>({...a,[d]:applicableVariables(pathology).filter(v=>v.dimension===d).reduce((n,v)=>n+pointsFor(v.id,answers[v.id]),0)}),{} as Record<Dimension,number>)}
export function determinePriorityByScore(score:number):Priority{return score<=PRIORITY_CUTS.priority3Max?3:score<=PRIORITY_CUTS.priority2Max?2:1}
export function applyMandatoryRules(answers:Answers){if(answers.age==='minor')return {pediatric:true,priority:null as Priority|null,reason:'Para pacientes menores de 18 años debe utilizarse la Adaptación del Modelo CMO al paciente crónico pediátrico.'};if(answers.advanced_therapy==='yes')return {pediatric:false,priority:1 as Priority,reason:'Tratamiento con terapia génica/terapia avanzada.'};return {pediatric:false,priority:null as Priority|null,reason:''}}
export function determineFinalPriority(answers:Answers,pathology?:Pathology,professional?:{enabled:boolean;priority:1|2;reason:string}){const score=calculateScore(answers,pathology),byScore=determinePriorityByScore(score),mandatory=applyMandatoryRules(answers);if(mandatory.pediatric)return{score,byScore:null,final:null,reason:mandatory.reason,pediatric:true};let final=mandatory.priority??byScore;let reason=mandatory.reason;if(professional?.enabled&&professional.reason.trim()&&professional.priority<final){final=professional.priority;reason=[reason,`Elevación por criterio profesional: ${professional.reason}`].filter(Boolean).join(' ')}return{score,byScore,final,reason,pediatric:false}}
